### ISSUE TITLE
AttributeError: module 'baselines.common.tf_util' has no attribute 'get_session'

### ISSUE THREAD

**Issue by yanzhenqiang** [rddy/deepassist#1]
170     # Create all the functions necessary to train the model
    171 
    172     sess = U.get_session()
    173     if sess is None:
    174         sess = U.make_session(num_cpu=num_cpu)

AttributeError: module 'baselines.common.tf_util' has no attribute 'get_session'

**Comment by rddy** [comment]
I would recommend trying baselines 0.1.4

**Comment by yanzhenqiang** [comment]
when changing to baselines==0.1.4， this error occur：
TypeError: build_train() got an unexpected keyword argument 'param_noise'

**Comment by yanzhenqiang** [comment]
I comment 'param_noise' and use gym==0.7.4 ,the code runs

**Comment by aghosh16** [comment]
May I know yanzhenqiang what exactly you did to run the code? I used Baselines 0.1.4 and gym 0.9.1 and got the same error TypeError: build_train() got an unexpected keyword argument 'param_noise'.
