### ISSUE TITLE
Problems of version of python dependencies

### ISSUE THREAD

**Issue by XZHSTAX** [rddy/deepassist#8]
when I use `pip install -r requirements.txt` to install python dependencies, it reminds me that 
```
ERROR: Cannot install -r requirements.txt (line 9) and gym==0.7.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested gym==0.7.4
    baselines 0.1.4 depends on gym>=0.9.1[all]
```
so I change `gym==0.7.4` to `gym==0.9.1` and install the dependencies successfully.

then I got another problems about the version of baselines. `requirements.txt` said that right version of baselines should be 0.1.4.

but in your code `1.0-lunarlander-sim.ipynb`, you use some parameters that not been added until 0.1.5 like `scope` in `deepq.learn` so I updata the version of baselines to 0.1.5.

then another problem appear, in your code `simple.py` you use some function that exist in 0.1.4 but deleted in 0.1.5 like `get_session()` 

I read your paper and find this code, you work is super cool and I really want to learn more about your work, So would you please check and give a new requirement?

**Comment by rddy** [comment]
try https://github.com/rddy/deepassist/issues/2

**Comment by XZHSTAX** [comment]
I use python 3.6.13 under Ubuntu 20.04.4 LTS
here is my [requirement.txt](https://github.com/rddy/deepassist/files/8393998/requirement.txt)
in `simple.py`, comment line 187.
in `1.0-lunarlander-sim.ipynb` and `1.2-lunarlander-human.ipynb`, the function `co_dqn_learn`,variates `human_agent_action` and `human_agent_active` are global twice,fix it 
then you can enjoy this cool project

**Comment by HEI-JIAN** [comment]
Have you ever had this problem in the 1.0-lunarlander-sim.
2023-04-25 23:45:24.997026: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key pretrained_noop_copilot_scope/eps not found in checkpoint
tensorflow.python.framework.errors_impl.NotFoundError: Key pretrained_noop_copilot_scope/eps not found in checkpoint
	 [[{{node save_316/RestoreV2}}]]


could you give me some advice? Thank you very much.

**Comment by XZHSTAX** [comment]
sorry, i didn't meet this problem, it seems that there is something wrong when saving the model, maybe it's related to tf1's static graph. I believe there would be better solution on stackoverflow. Good luck!
